import { Movie } from '../types/movie';

export const CURATED_LANDMARKS: Movie[] = [
  {
    id: 693134,
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    releaseDate: '2024-02-27',
    runtime: 166,
    posterPath: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: '/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg',
    voteAverage: 8.2,
    voteCount: 5200,
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 12, name: 'Adventure' }],
    status: 'Released',
    tagline: 'Long live the fighters.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    releaseDate: '2023-07-19',
    runtime: 181,
    posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: '/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg',
    voteAverage: 8.1,
    voteCount: 8900,
    genres: [{ id: 18, name: 'Drama' }, { id: 36, name: 'History' }],
    status: 'Released',
    tagline: 'The world forever changes.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 157336,
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    releaseDate: '2014-11-05',
    runtime: 169,
    posterPath: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    voteAverage: 8.4,
    voteCount: 34500,
    genres: [{ id: 12, name: 'Adventure' }, { id: 18, name: 'Drama' }, { id: 878, name: 'Sci-Fi' }],
    status: 'Released',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 27205,
    title: 'Inception',
    originalTitle: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\".',
    releaseDate: '2010-07-15',
    runtime: 148,
    posterPath: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropPath: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    voteAverage: 8.4,
    voteCount: 36200,
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }, { id: 12, name: 'Adventure' }],
    status: 'Released',
    tagline: 'Your mind is the scene of the crime.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 335984,
    title: 'Blade Runner 2049',
    originalTitle: 'Blade Runner 2049',
    overview: 'Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\'s left of society into chaos.',
    releaseDate: '2017-10-04',
    runtime: 164,
    posterPath: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdropPath: '/ilRyASDvt7v69h52bTIc94F9LzP.jpg',
    voteAverage: 8.0,
    voteCount: 13200,
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 18, name: 'Drama' }],
    status: 'Released',
    tagline: 'There\'s still a page left.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 155,
    title: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of allies Lt. Jim Gordon and DA Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    releaseDate: '2008-07-16',
    runtime: 152,
    posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropPath: '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
    voteAverage: 8.5,
    voteCount: 32400,
    genres: [{ id: 18, name: 'Drama' }, { id: 28, name: 'Action' }, { id: 80, name: 'Crime' }, { id: 53, name: 'Thriller' }],
    status: 'Released',
    tagline: 'Why So Serious?',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 496243,
    title: 'Parasite',
    originalTitle: '기생충',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    releaseDate: '2019-05-30',
    runtime: 133,
    posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdropPath: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    voteAverage: 8.5,
    voteCount: 17800,
    genres: [{ id: 35, name: 'Comedy' }, { id: 53, name: 'Thriller' }, { id: 18, name: 'Drama' }],
    status: 'Released',
    tagline: 'Act like you own the place.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 129,
    title: 'Spirited Away',
    originalTitle: '千と千尋の神隠し',
    overview: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
    releaseDate: '2001-07-20',
    runtime: 125,
    posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdropPath: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    voteAverage: 8.5,
    voteCount: 16100,
    genres: [{ id: 16, name: 'Animation' }, { id: 10751, name: 'Family' }, { id: 14, name: 'Fantasy' }],
    status: 'Released',
    tagline: 'Tunnel to the other world.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 238,
    title: 'The Godfather',
    originalTitle: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.',
    releaseDate: '1972-03-14',
    runtime: 175,
    posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropPath: '/tmU7GeKVybMWF92GlF1vtG0whY9.jpg',
    voteAverage: 8.7,
    voteCount: 20200,
    genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
    status: 'Released',
    tagline: 'An offer you can\'t refuse.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    originalTitle: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
    releaseDate: '1994-09-10',
    runtime: 154,
    posterPath: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropPath: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    voteAverage: 8.5,
    voteCount: 27400,
    genres: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }],
    status: 'Released',
    tagline: 'Just because you are a character doesn\'t mean that you have character.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 244786,
    title: 'Whiplash',
    originalTitle: 'Whiplash',
    overview: 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
    releaseDate: '2014-10-10',
    runtime: 107,
    posterPath: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    backdropPath: '/fRGxZuo0jGUurwGsmKofYF5krmd.jpg',
    voteAverage: 8.4,
    voteCount: 14800,
    genres: [{ id: 18, name: 'Drama' }, { id: 10402, name: 'Music' }],
    status: 'Released',
    tagline: 'The road to greatness can take you to the edge.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 545611,
    title: 'Everything Everywhere All at Once',
    originalTitle: 'Everything Everywhere All at Once',
    overview: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what\'s important to her by connecting with the lives she could have led in other universes.',
    releaseDate: '2022-03-24',
    runtime: 139,
    posterPath: '/w3LxiVYPqrlexMm0107h912upZ1.jpg',
    backdropPath: '/707thQazSnOw09gm072x7BcqLkr.jpg',
    voteAverage: 7.8,
    voteCount: 6100,
    genres: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }, { id: 878, name: 'Sci-Fi' }],
    status: 'Released',
    tagline: 'The universe is so much bigger than you realize.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    originalTitle: 'Spider-Man: Into the Spider-Verse',
    overview: 'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops superpowers.',
    releaseDate: '2018-12-06',
    runtime: 117,
    posterPath: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    backdropPath: '/7d6o00VzY4mZk3tUj07Yh65jK70.jpg',
    voteAverage: 8.4,
    voteCount: 15300,
    genres: [{ id: 16, name: 'Animation' }, { id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }],
    status: 'Released',
    tagline: 'More than one wears the mask.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 329865,
    title: 'Arrival',
    originalTitle: 'Arrival',
    overview: 'Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.',
    releaseDate: '2016-11-10',
    runtime: 116,
    posterPath: '/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    backdropPath: '/vL5LR6WdxWPjC37L5pXom4K95K.jpg',
    voteAverage: 7.6,
    voteCount: 17200,
    genres: [{ id: 18, name: 'Drama' }, { id: 878, name: 'Sci-Fi' }, { id: 9648, name: 'Mystery' }],
    status: 'Released',
    tagline: 'Why are they here?',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 76341,
    title: 'Mad Max: Fury Road',
    originalTitle: 'Mad Max: Fury Road',
    overview: 'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life.',
    releaseDate: '2015-05-13',
    runtime: 120,
    posterPath: '/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
    backdropPath: '/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg',
    voteAverage: 7.6,
    voteCount: 22100,
    genres: [{ id: 28, name: 'Action' }, { id: 12, name: 'Adventure' }, { id: 878, name: 'Sci-Fi' }],
    status: 'Released',
    tagline: 'What a Lovely Day.',
    lastFetched: new Date().toISOString(),
  },
  {
    id: 62,
    title: '2001: A Space Odyssey',
    originalTitle: '2001: A Space Odyssey',
    overview: 'Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world\'s most advanced supercomputer.',
    releaseDate: '1968-04-02',
    runtime: 149,
    posterPath: '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg',
    backdropPath: '/w5COQk6uQ4sT8VzR1j8jY9X2b9O.jpg',
    voteAverage: 8.1,
    voteCount: 11300,
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 9648, name: 'Mystery' }, { id: 12, name: 'Adventure' }],
    status: 'Released',
    tagline: 'The Ultimate Trip.',
    lastFetched: new Date().toISOString(),
  },
];
